version: 2
updates:
    - package-ecosystem: npm
      directory: '/core-sdk-samples/higgs-shop-sample-app/'
      schedule:
        interval: daily
        time: "08:00"
        timezone: "America/New_York"
      target-branch: 'development'
      labels: ['dependabot']
      open-pull-requests-limit: 10
