name: Deploy Higgs Shop to Github Pages

on:
    workflow_run:
        workflows: ['Release Higgs Shop']
        types:
            - completed
        branches:
            - main

defaults:
    run:
        working-directory: core-sdk-samples/higgs-shop-sample-app

jobs:
    deploy-github-pages:
        name: Deploy Higgs Shop to Github Pages
        if: >
            ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        env:
            GIT_AUTHOR_NAME: mparticle-automation
            GIT_AUTHOR_EMAIL: developers@mparticle.com
            GIT_COMMITTER_NAME: mparticle-automation
            GIT_COMMITTER_EMAIL: developers@mparticle.com
        steps:
            - name: Check out main Branch
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm ci

            - name: Deploy to Github Pages
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm run deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}

            - name: Archive npm failure logs
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: npm-logs
                  path: ~/.npm/_logs
