name: "Pull Request Checks"

on: [ push, workflow_dispatch, pull_request ]

jobs:

  higgs-shop-sample-app:
    name: "Check Higgs Shop Sample App PR"
    uses: ./.github/workflows/higgs-shop-sample-app-pull-request.yml
    with:
      app_relative_path: "core-sdk-samples/higgs-shop-sample-app"

  automerge-dependabot:
    name: "Save PR Number for Dependabot Automerge"
    needs: [ higgs-shop-sample-app ]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout PR branch"
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: "Save Pull Request Number"
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
