name: "Pull Request Checks"

on: [ pull_request_target ]

jobs:

  higgs-shop-sample-app:
    name: "Check Higgs Shop Sample App PR"
    uses: ./.github/workflows/higgs-shop-sample-app-pull-request.yml
    with:
      app_relative_path: "core-sdk-samples/higgs-shop-sample-app"

  automerge-dependabot:
    name: "Automerge Dependabot PR"
    needs: [ higgs-shop-sample-app ]
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mparticle-bot
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-bot
      GIT_COMMITTER_EMAIL: developers@mparticle.com
    runs-on: ubuntu-latest
    steps:
      - name: "Rebase Dependabot PR"
        uses: actions/github-script@v3
        with:
          script: |
            github.pulls.merge({
                owner: context.repo.owner,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                merge_method: 'rebase'
            });
  rebase-development:
      name: "Rebase Development onto Dependabot Branch"
      needs: [ automerge-dependabot ]
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: mParticle/mparticle-workflows/.github/workflows/dependabot-rebase-development.yml@stable
